version: '3'

services:
  # O nome do service deverá ser todotests;
  todotests:
    # Lembrando que, dentro de uma rede docker, o host de um container é identificado pelo seu nome.
    build: ./todo-app/tests

    # O container de todotests deve ter como dependencia os containers frontend e backend;
    depends_on:
      - todoback
      - todofront
    restart: always

    # Deve ter uma variável de ambiente FRONT_HOST que recebe como valor o nome do container do frontend
    environment:
      - FRONT_HOST=todofront

    # O nome do service deverá ser todofront;
    todofront:
      depends_on:
        - todoback

      # Lembrando que, dentro de uma rede docker, o host de um container é identificado pelo seu nome.
      build: ./todo-app/front-end
      restart: always

      # Deve ter como dependencia o container backend;
      environment:
        # Deve ter uma variável de ambiente REACT_APP_API_HOST que recebe como valor o nome do container do backend.
        - REACT_APP_API_HOST=todoback
        - REACT_APP_API_PORT=3001

      # O container de todofrontend deve rodar na porta 3000;
      ports:
        - 3000:3000

    # O nome do service deverá ser todoback;
    todoback:
      build: ./todo-app/back-end
      restart: always
      # O container de todobackend deve rodar na porta 3001;
      ports:
        - 3001:3001
